### ISSUE TITLE
Exposed Hash by 755 permission

### ISSUE THREAD

**Issue by minhoryang** [taeguk/terminal_lock_system#1]
https://github.com/taeguk/terminal_lock_system/blob/master/install_tls.py#L46

**Comment by taeguk** [comment]
oh my mistake! thank you. 고마워요 민호형 ㅋㅋ

**Comment by minhoryang** [comment]
시험기간에 너무 공부하기 싫었어ㅋㅋㅋㅋㅋㅋㅋㅋ 재밌는거 많이하네ㅋㅋ

**Comment by taeguk** [comment]
ㅋㅋㅋㅋ 걍 심심할 때 간단한거 이것저것 만들어요 ㅎㅎ
